### ISSUE TITLE
Variable global_domain_name is only accepted when twice quoted

### ISSUE THREAD

**Issue by bertvv** [bertvv/ansible-role-dhcp#1]
```Yaml
# expected:
dhcp_global_domain_name: example.com
# or:
dhcp_global_donain_name: 'example.com'
# currently accepted:
dhcp_global_donain_name: '"example.com"'
```

The fact that the domain name is quoted twice is silly. A small change in the config file template will fix this.
