### ISSUE TITLE
DHCP Host Options

### ISSUE THREAD

**Issue by minitriga** [bertvv/ansible-role-dhcp#28]
Hello, 

This is a great role, I'm looking to use it for a little project I have whereby I use it to specify network hosts for zero touch configuration on Juniper devices.

[This can be seen here](https://www.juniper.net/documentation/en_US/junos/topics/topic-map/zero-touch-provision.html#id-zero-touch-provisioning)

However, to use this you must use the vendor option space. Do you have any thoughts on how to easily add something like the following to part of the `dhcp.conf` file?
```
option space NEW_OP; option; 
option NEW_OP.image-file-name code 0 = text; 
option NEW_OP.config-file-name code 1 = text; 
option NEW_OP.image-file-type code 2 = text; 
option NEW_OP.transfer-mode code 3 = text; 
option NEW_OP.alt-image-file-name code 4= text; 
option NEW_OP.http-port code 5= text;
option NEW_OP-encapsulation code 43 = encapsulate NEW_OP;
```

and then using variables such as (Cut down):

```
dhcp_hosts:
  - name: Juniper1
    mac: '00:11:22:33:44:55'
    ip: 192.168.222.150
    options:
        - name: NEW_OP.image-file-name
           value: /dist/images/jinstall-ex-4200-13.2R1.1-domestic-signed.tgz
        - name:NEW_OP.config-file-name
           value: /dist/config/jn-switch35.config
```

which would then result in the following config in ISC:

```
host jn-switch35 {
     hardware ethernet ac:4b:c8:29:5d:02;
     fixed-address 10.100.31.36;
     option tftp-server-name "10.100.31.71";
     option host-name "jn-switch35";
     option log-servers 10.100.31.72;
     option ntp-servers 10.100.31.73;
     option NEW_OP.image-file-name "/dist/images/jinstall-ex-4200-13.2R1.1-domestic-signed.tgz";
     option NEW_OP.transfer-mode "ftp";
     option NEW_OP.config-file-name "/dist/config/jn-switch35.config";
     option NEW_OP.jloader-file "jloader-qfx-5-14.1X53-D26-signed.tgz";
}
```

any thoughts would be helpful.
