### ISSUE TITLE
When using ansible with root account verification fails

### ISSUE THREAD

**Issue by yuergen** [bertvv/ansible-role-dhcp#41]
Since there is internet police officer in my homelab, I use the root account with ansible.

Verification of the dhcp configuration fails, because the AppArmor fix only applies to user directories located within /home.

Adding a task to apply the AppArmor fix to root's home directory, too, is necessary:
```
- name: AppArmor fix | Ensure dhcpd can acces temp config file for validation (3/3)
  lineinfile:
    dest: "{{ dhcp_apparmor_policy }}"
    line: '  /root/.ansible/** r,'
    insertbefore: '.*/etc/dhcp/ r,'
    state: present
    create: false
  when: apparmor_policyfile.stat.exists
  failed_when: false
  #register: apparmor_fix_2
  notify: restart apparmor
  tags: dhcp
```
